import {
  ArrowLeft,
  ArrowsOut,
  ArrowUpRight,
  CaretDown,
  BookOpenText,
  Books,
  Brain,
  ChatsCircle,
  ChatCircle,
  Check,
  Code,
  Copy,
  Cpu,
  DotsThreeVertical,
  Export,
  DownloadSimple,
  Globe,
  FileDoc,
  FilePdf,
  UploadSimple,
  Flask,
  FunnelSimple,
  Gear,
  GitBranch,
  HandPointing,
  Keyboard,
  MagnifyingGlass,
  MegaphoneSimple,
  Minus,
  Note,
  PencilSimple,
  Play,
  Plus,
  Presentation,
  PushPin,
  RocketLaunch,
  ShareNetwork,
  Storefront,
  Table,
  Trash,
  TreeStructure,
  UserCircleGear,
  WebhooksLogo,
  Wrench,
  X,
  Info,
  Clock,
  FloppyDisk,
  Scales,
  ChartBar,
  Tag,
  CurrencyDollar,
} from '@phosphor-icons/react';

/** Phosphor components keyed by stable app names (not file paths). */
export const ICON_REGISTRY = {
  back: ArrowLeft,
  feedback: MegaphoneSimple,
  test: Flask,
  save: FloppyDisk,
  launch: RocketLaunch,
  publish: ArrowUpRight,
  zoomOut: Minus,
  zoomIn: Plus,
  storefront: Storefront,
  sessions: ChatsCircle,
  tools: Wrench,
  search: MagnifyingGlass,
  globe: Globe,
  filter: FunnelSimple,
  plus: Plus,
  moreVertical: DotsThreeVertical,
  trash: Trash,
  share: ShareNetwork,
  copy: Copy,
  edit: PencilSimple,
  pin: PushPin,
  guide: BookOpenText,
  settings: Gear,
  // Node palette / workflow types
  'sticky-note': Note,
  chat: ChatCircle,
  agent: Cpu,
  'code-executor': Code,
  'powerpoint-generator': Presentation,
  condition: GitBranch,
  branches: TreeStructure,
  'human-in-the-loop': UserCircleGear,
  hitl: HandPointing,
  researcher: MagnifyingGlass,
  'business-analyst': ChartBar,
  'data-classifier': Tag,
  'financial-modeler': CurrencyDollar,
  'ai-judge': Scales,
  'pdf-generator': FilePdf,
  'excel-generator': Table,
  webhook: WebhooksLogo,
  'scheduled-start': Clock,
  'manual-input': Keyboard,
  start: Play,
  output: Export,
  end: Export,
  brain: Brain,
  kb: Books,
  check: Check,
  fitScreen: ArrowsOut,
  chevronDown: CaretDown,
  caretDown: CaretDown,
  workflow: TreeStructure,
  fileDoc: FileDoc,
  upload: UploadSimple,
  download: DownloadSimple,
  exportFile: Export,
  close: X,
  info: Info,
};

/** Legacy `/icons/*.svg` paths → registry keys. */
export const ICON_PATH_ALIASES = {
  '/icons/back.svg': 'back',
  '/icons/feedback.svg': 'feedback',
  '/icons/test-chat.svg': 'test',
  '/icons/save-check.svg': 'save',
  '/icons/launch-arrow.svg': 'launch',
  '/icons/zoom-minus.svg': 'zoomOut',
  '/icons/zoom-plus.svg': 'zoomIn',
  '/icons/tab-storefront.svg': 'storefront',
  '/icons/tab-sessions.svg': 'sessions',
  '/icons/tab-mytools.svg': 'tools',
  '/icons/search.svg': 'search',
  '/icons/filter-sort.svg': 'filter',
  '/icons/plus.svg': 'plus',
  '/icons/more-vertical.svg': 'moreVertical',
  '/icons/delete-trash.svg': 'trash',
  '/icons/share.svg': 'share',
  '/icons/copy.svg': 'copy',
  '/icons/edit-square.svg': 'edit',
  '/icons/sticky-note.svg': 'sticky-note',
  '/icons/chat.svg': 'chat',
  '/icons/agent.svg': 'agent',
  '/icons/code-executor.svg': 'code-executor',
  '/icons/powerpoint-generator.svg': 'powerpoint-generator',
  '/icons/condition.svg': 'condition',
  '/icons/branches.svg': 'branches',
  '/icons/human-in-the-loop.svg': 'human-in-the-loop',
  '/icons/researcher.svg': 'researcher',
  '/icons/business-analyst.svg': 'business-analyst',
  '/icons/data-classifier.svg': 'data-classifier',
  '/icons/financial-modeler.svg': 'financial-modeler',
  '/icons/ai-judge.svg': 'ai-judge',
  '/icons/pdf-generator.svg': 'pdf-generator',
  '/icons/excel-generator.svg': 'excel-generator',
  '/icons/webhook.svg': 'webhook',
  '/icons/scheduled-start.svg': 'scheduled-start',
  '/icons/database.svg': 'agent',
  '/icons/check-circle.svg': 'save',
};

export function resolveIconName(nameOrPath) {
  if (!nameOrPath) return null;
  if (ICON_REGISTRY[nameOrPath]) return nameOrPath;
  if (ICON_PATH_ALIASES[nameOrPath]) return ICON_PATH_ALIASES[nameOrPath];
  return null;
}
